### ISSUE TITLE
Команда build-storybook называется не по конвенции

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/utils#10]
build-storybook -> build:storybook

**Comment by etroynov** [comment]
Можно ссылку на доку для закрепления в readme?

**Comment by stepancar** [comment]
@etroynov конвенция находится в приватных стандартах. 
Начало конвенции положил ты в одном из реквестов

**Comment by etroynov** [comment]
я помню, просто решил уточнить может ссылку можно добавить сюда. Добавлю в вики.

**Comment by etroynov** [comment]
добавил в [вики](https://github.com/alfa-laboratory/utils/wiki/%D0%9E%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%B4%D0%B0).
