### ISSUE TITLE
Создать библиотеку типов

### ISSUE THREAD

**Issue by etroynov** [alfa-laboratory/utils#14]
# Описание
Предлагаю добавить пакет для хранения общих типов.

# Чек лист
- [ ] Документация

# Дополнительная информация
<p>AMOUNT</p>
<img src="https://cs.pikabu.ru/post_img/2013/01/27/5/1359268459_542111991.jpg" />

## Есть ли у вас возможность принять участие в разработке?
- Да

**Comment by lisovskyR** [comment]
у нас в проектах есть дженерик тип для экшенов:
```
export type InferValueTypes<T> = T extends { [key: string]: infer U } ? U : never;
// TODO: extract somewhere
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type GenericActionCreator<T extends { [key: string]: any }> = ReturnType<InferValueTypes<T>>;
```
который мы потом используем как
```
import * as actions from 'actions/creators/card-blocking';
type Action = GenericActionCreator<typeof actions>;
```

**Comment by etroynov** [comment]
сделано
