### ISSUE TITLE
Утилита для форматирования российского номера телефона

### ISSUE THREAD

**Issue by aleksey-ilin** [alfa-laboratory/utils#16]
# Описание
Предлагаю добавить утилиту для форматирования российского номера телефона

# Поведение
Поведение описано в этом [issue](https://github.com/alfa-laboratory/core-components/issues/191)

# Чек лист
- [ ] Тесты
- [ ] Документация

**Comment by aso1datov** [comment]
Надо уточнить, что утилита именно для **российского** номера телефона

**Comment by etroynov** [comment]
да иностранные номера тоже интересуют.

**Comment by etroynov** [comment]
@aleksey-ilin есть новости ?

**Comment by aleksey-ilin** [comment]
если честно не уверен что эту утилиту надо вытаскивать из компонента, потому что:
1) не представляю где ее можно использовать отдельно от компонента
2) правила форматирования периодически меняются, неделю назад дизайнеры и ребята с сайта планировали тестировать разное форматирования, но пока от них информации нет
@etroynov  как думаешь лучше поступить с этой утилитой?

**Comment by aleksey-ilin** [comment]
Предлагаю добавить две функции для форматирования номера телефона.

1) `getRawPhoneNumber` - удаляет любые символы из номера телефона и возвращает его в формате `71112223344`. Нужна для использования в компонентах и передачи в запросах.
2) `formatPhone` - форматирование номера телефона по маске в формат `+7 111 222-33-44`.
