### ISSUE TITLE
Необходима утилита для возврата укороченного номера счёта

### ISSUE THREAD

**Issue by aso1datov** [alfa-laboratory/utils#24]
# Описание
Предлагаю добавить новую утилиту для возврата последних 4-х символов номера счёта в формате ··4768

# Поведение
Передаем строку с номером счёта, например 40817810210210285256, получаем на выходе ··5256

# Чек лист
- [x] Тесты
- [x] Документация

# Дополнительная информация
Дополнительная информация

## Есть ли у вас возможность принять участие в разработке?
- Да

**Comment by etroynov** [comment]
у нас вроде есть утилита для форматирования счета, может добавить в нее параметр для укорачивания?
