### ISSUE TITLE
Что мы хотим здесь видеть

### ISSUE THREAD

**Issue by lisovskyR** [alfa-laboratory/utils#3]
Нужно решить что конкретно мы хотим сюда тащить и почему, потом можно попробовать запихать пр с несколькими примерами и посмотреть как пойдет

из того что озвучивалось:
- обшие утилсы: например, pluralize
- хуки
- хоки (с ними до конца не решили, будут ли они здесь или нет)

**Comment by lisovskyR** [comment]
мне кажется, хоки тоже стоит затащить, потому что так и не придумали, куда их можно пристроить

**Comment by avkvak** [comment]
Хуки и хоки, по логике вещей, очень родственные друг другу вещи. 
Одно призвано избавиться от hoc-hell. 
На мой взгляд, нет ни одного повода разделять хоки и хуки по разным репозиториям. 
В то же время, как мне кажется, нет ни одного повода писать хоки в принципе.

**Comment by etroynov** [comment]
С очень большой вероятностью хоков не будет т.к популяризатор хоков и разработчик https://github.com/acdlite/recompose депрекейтнул либу и перешел в кор тиму реакта пилить хуки.

В связи с этим я не вижу смысла в HOC.

**Comment by etroynov** [comment]
> мне кажется, хоки тоже стоит затащить, потому что так и не придумали, куда их можно пристроить

никуда и я не понимаю почему их до сих пор используют.
