### ISSUE TITLE
usePrevious возвращает некорректный тип

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/utils#5]
Сейчас usePrevious возвращает `any` вместо передаваемого типа.

https://github.com/alfa-laboratory/utils/blob/cdc8afd04fca71d6b2a88438f65a1eadb73f536b/packages/hooks/src/usePrevious.ts#L4

## Возможное решение

заменить `any` на `T`

--- 
P.S. в этом репозитории можно сразу в мастер?

**Comment by etroynov** [comment]
> P.S. в этом репозитории можно сразу в мастер?;

нет.

**Comment by ethorz** [comment]
Если неактуально, может закрыть ишью?

**Comment by etroynov** [comment]
исправлено #27
