### ISSUE TITLE
Форматирование 10000.22 RUR в 10 000,22 ₽

### ISSUE THREAD

**Issue by lisovskyR** [alfa-laboratory/utils#6]
# Описание
Нужно ваше мнение, понадобится ли такой утил, потому что сейчас есть только formatAmount, который работает с типом Amount. А эта утилита форматирует просто число и код символа

# Поведение
Приводит число 10000.22 и код символа RUR в 10 000,22 ₽

# Чек лист
- [ ] Тесты
- [ ] Документация

# Дополнительная информация
для использования понадобится splitAmount из core-components, и getCurrencySymbol из фижера (или если его тоже перенесли в кор)
```
export const formatAmountString = (amountString: string, currencyCode: string) => {
    const formattedAmount = splitAmount(amountString).replace('.', ',');
    return `${formattedAmount}\u00A0${getCurrencySymbol(currencyCode)}`;
};
```

## Есть ли у вас возможность принять участие в разработке?
- Да

**Comment by etroynov** [comment]
А почему дробная часть сбрасывается в 00 а не переводится в ,22?

**Comment by lisovskyR** [comment]
1. Пока да, но если нужно, можно добавить ей опций
2. Опечатка, поправил, дробные части остаются, конечно
3. splitAmount уже перенесли в кор, вроде, так что других зависимостей тянуть не нужно будет

**Comment by lisovskyR** [comment]
Вообще подобная штука понадобилась, потому что splitAmount из библиотеки не экспортируется а используется только внутри других утилов. Поэтому и создал issue, чтобы узнать, понадобится ли кому-нибудь подобный функционал, или это моя локальная проблема, и я оставлю это решение локально у себя

**Comment by stepancar** [comment]
@lisovskyR откуда пришла строка "10000.22" и код символа RUR?

**Comment by stepancar** [comment]
Обсудили, такого кейсы быть не должно

**Comment by etroynov** [comment]
Фича открыта по причине незавершенного PR.

**Comment by lisovskyR** [comment]
Этот issue не относился к ПР. Я его создал т.к. использовал локальное решение и подумал, что оно может понадобиться в дальнейшем, но мы решили, что это решение неверное и будем переделывать. Соответственно issue можно закрыть

**Comment by etroynov** [comment]
Но @stepancar ссылается в своем PR на данное issue по этой причине я его слинковал.

**Comment by lisovskyR** [comment]
думаю, он сначала слинковал, когда этот issue был актуален, а потом мы с ним решили, что проблема в другом. @stepancar проясни ситуацию
