### ISSUE TITLE
Позволить юзать formatAmount без currency

### ISSUE THREAD

**Issue by reme3d2y** [alfa-laboratory/utils#61]
У нас появился запрос на NumberInput, который как AmountInput, но про числа, а не деньги. Например инпут для ввода процентов.

У нас есть formatAmount, который в принципе подходит, но требует currency.
Собственно, предлагаю сделать параметр currency необязательным)

**Comment by stepancar** [comment]
Я предлагаю полностью делить. Это супер разные вещи
